### ISSUE TITLE
/docs redirects to /docs/

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge.github.io#165]
Either we should update links to include last slash, or change it up so `/docs` actually loads without redirecting.

**Comment by astorije** [comment]
> Either we should update links to include last slash

I'd rather not do that.

Moving `docs.md` is also not an option as it messed things up (I don't remember what exactly) and was quite a pain.

Is it really a problem?
Do you want me to port https://github.com/thelounge/thelounge.github.io/pull/84/commits/ef7f3c041e3b7077911a92048f2b5bf5d5e75821 over? I'm not sure if that's going to change anything.

**Comment by astorije** [comment]
> It only affects the link in the navbar, I'm not sure why you don't want to add a slash if it gets redirected?

I don't understand why this is suddenly a problem. We've had that since day 1 and it has never been a problem. Reason why I prefer `/docs` is for consistency with other top level-pages such as `/community` (and future ones I've started to work on), but I'm just confused as to why this super tiny thing is being a problem 😅

I was playing with `curl`, and am getting confused `curl https://thelounge.chat/docs` and `curl https://thelounge.chat/docs` both return the HTML content while `curl http://shout-irc.com/docs` returns an HTML page with `301 Moved Permanently`.
When checking their code with `curl -I`, all give a 301 while `/docs/` gives a 200. The browser also seems to be getting a 301.
I'm confused, does the difference in curl come from HTTP/2 (Netlify) vs. HTTP/1.1 (GitHub Pages)?

> I can only think of Getting Started not showing up in the sidebar menu, unless there's other problems?

That's a major one, the extra piece required to overcome this does not offset the redirect IMO. I am also trying to do something that is not compatible with it.
All in all, this is even less desirable than adding the `/`...
