### ISSUE TITLE
Guide - Install for Windows - WIP

### ISSUE THREAD

**Issue by aab12345** [thelounge/thelounge.github.io#250]
**Issue**: to be tagged as documentation

I am looking myself into creating a full guide for windows users that might feel left out a little on how to get the lounge set up from start to finish.  

This guide will fully support:
- [ ] Windows 10, Windows 11 and Server 64 Bit OS installations.
- [ ] Batch script to install the core automatically.
- [ ] A simple batch script to start the service once fully installed.
- [ ] A manual way on how to install it, section by section.

Has anyone actually wanted to get the lounge up and running on windows OS 
.. or failed or would like to know more information about it?

**Comment by Raventhicc** [comment]
With the help of a few people in `#thelounge` (great thanks to Activ8)  I've got TheLounge working on Windows 11 Pro 21H2.

1. Start with `https://thelounge.chat/docs/install-and-upgrade#from-npm-releases`
2. Create user/pass
3. You should now have TheLounge working. You can stop here since its working but I personally didnt like the fact that i had to have terminal open while its running and the fact that I had to manually launch it. To avoid that follow ahead.
4. Close the terminal.
5. Create a new text file, just add `thelounge start` in the text file and save it.
6. Rename that file to file to anything you want, for convenience I'll name it `lounge`. Important part is change the `.txt` to `.bat` (i.e, `lounge.txt` -> `lounge.bat`). Windows will prompt you that changing the extension can make it unusable but ignore it and rename it.
7. To test your bat script, double click `lounge.bat` (or whatever you named it). It should launch terminal and start `theLounge` server. 
8. Close terminal.
9. Create a new text file and paste this into it:
```
Set WshShell = CreateObject("WScript.Shell") 
WshShell.Run chr(34) & "path\to\your .bat file" & Chr(34), 0
Set WshShell = Nothing
```
Replace `"path\to\your .bat file"` with the path of your `.bat` file
So for example:
I saved the `lounge.bat`  file in Documents. Right-click it in Windows 11 and click `Copy As Path` (For Windows 10, the `Copy As Path` option won't show up when simply right-clicking. Do `SHIFT+Right Click` and this time you'll see a bunch of extra options including `Copy As Path`. Path has been copied to your clipboard (something like `"C:\Users\username\Documents\lounge.bat"` and now just replace the placeholder path.
It should look like this after editing:

 ```
Set WshShell = CreateObject("WScript.Shell") 
WshShell.Run chr(34) & "C:\Users\username\Documents\lounge.bat" & Chr(34), 0
Set WshShell = Nothing
```
10. Save the file. 
11. Rename that file to file to anything you want, for convenience I'll name it `launch_lounge`. Important part is change the `.txt` to `.vbs` (i.e, `launch_lounge.txt` -> `launch_lounge.vbs`). Windows will prompt you that changing the extension can make it unusable but ignore it and rename it.
12. Now double click `launch_lounge.vbs` (again whatever name you gave it as long as the extension is `.vbs`). Nothing should show up but you should be able to connect Lounge IRC from your browser now. You can check if its running by going to Task Manager and look for `Node.js JavaScript Runtime`.
13. The First problem has been solved, that was, having the terminal open in the foreground. It's still running but now in background which is what i prefer.
14. You can use the .vbs file you just created as a launcher but i would prefer it launches at startup so ill use Task Scheduler.
15. Search "Task Scheduler" in Windows
16. Open it
17. On the Right Pane, go to Create Task and click it.
18. A new window will open. Give the task whatever name you want. Ill name it  theLoungeStartUp
19. Go to the next tab, Triggers
20. Click the New button
21.  New Window opens. Go to the top dropdown. I would want it to start at Windows StartUp, so ill change it from On a schedule to At startup but you can adjust it according to your needs
22. Save, move to next tab Actions
23. Click the New button
24. New Window Opens. Leave the dropdown at default, move to second field that is Program/Script, click the browse button and locate your .vbs file (NOT the .bat initially created)
25. Click Ok.
26. You should see the new task you created in the Task Scheduler Library. Click it, go to the right pane, click run.


All setup done. Now everytime PC starts, TheLounge Server will launch in background :D 

Side Note:
Other methods I tried but failed were installing it as a service through default Powershell and NSSM.

**Comment by aab12345** [comment]
Thanks for this, very precise info.  This is a step by step guide but don't want to commit this to the main website.  I feel it's a little long and a lot of steps but could easily condense it.  

Basically this guide is only to hide the command prompt window using schedule tasks.

Will look into gathering more information before I put up a windows guide.

**Comment by aab12345** [comment]
I have decided to keep this on my own GitHub page and close this as an issue.  There's little interest in it here but this is the link for future reference.

https://github.com/aab12345/thelounge-windows

/closed.
