### ISSUE TITLE
Switch lounge to thelounge in documentation

### ISSUE THREAD

**Issue by yzgyyang** [thelounge/thelounge.github.io#83]
`lounge` is deprecated in CLI, it is recommended to use `thelounge`. Documentation should be changed to reflect that.

**Comment by astorije** [comment]
Hey @yzgyyang, thanks for the report!
That's something I addressed in my branch https://github.com/thelounge/thelounge.github.io/tree/astorije/better-docs, the new docs being rewritten that I should be able to finish soon (no ETA).

I should open a PR so that there is a reference to it (and a preview build) instead of keeping it as a cryptic branch only, thanks for the nudge!

**Comment by xPaw** [comment]
Fixed by 8be34b30f617e4e29a0064f20e5afb3fafd53ada
